server:
  port: 8769
spring:
  application:
    name: eureak-monitor-client
turbine:
  appConfig: eureka-ribbon-client,euraka-feign-client
  clusterNameExpression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/