server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzydzydzy/spring-cloud.git
          search-paths: eureka-client
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
